server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://116.62.13.6:3306/cloud_project?serverTimezone=GMT%2B8
    username: mercer
    password: Justmyself957!

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
#  type-aliases-package: com.train.springcloud.entities