server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://116.62.13.6:3306/cloud_project?serverTimezone=GMT%2B8
    username: root
    password: Justmyself957!

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      单机版
      defaultZone: http://eureka7001.com:7001/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30