server:
  port: 8004
spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://116.62.13.6:3306/cloud_project?serverTimezone=GMT%2B8
    username: root
    password: Justmyself957!
  cloud:
    zookeeper:
      connect-string: 116.62.13.6:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30